// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlgen

import (
	"context"
	"time"
)

const pageRunEvents = `-- name: PageRunEvents :many
SELECT run_id, seq, type, schema_version, payload, created_at
FROM run_events
WHERE tenant_id = $1
  AND run_id = $2
  AND seq > $3
ORDER BY seq
LIMIT $4
`

type PageRunEventsParams struct {
	TenantID  string `json:"tenant_id"`
	RunID     string `json:"run_id"`
	AfterSeq  int64  `json:"after_seq"`
	PageLimit int32  `json:"page_limit"`
}

type PageRunEventsRow struct {
	RunID         string    `json:"run_id"`
	Seq           int64     `json:"seq"`
	Type          string    `json:"type"`
	SchemaVersion int32     `json:"schema_version"`
	Payload       []byte    `json:"payload"`
	CreatedAt     time.Time `json:"created_at"`
}

// Authorization, repeatable-read snapshot and future-cursor checks live in
// Store.Events. This query must run on that tenant-scoped transaction.
func (q *Queries) PageRunEvents(ctx context.Context, arg PageRunEventsParams) ([]PageRunEventsRow, error) {
	rows, err := q.db.Query(ctx, pageRunEvents,
		arg.TenantID,
		arg.RunID,
		arg.AfterSeq,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PageRunEventsRow{}
	for rows.Next() {
		var i PageRunEventsRow
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Type,
			&i.SchemaVersion,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
