// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: proto/runner/v1/runner.proto

package runnerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnerService_PrepareWorkspace_FullMethodName = "/forge.runner.v1.RunnerService/PrepareWorkspace"
	RunnerService_AdoptWorkspace_FullMethodName   = "/forge.runner.v1.RunnerService/AdoptWorkspace"
	RunnerService_StartOperation_FullMethodName   = "/forge.runner.v1.RunnerService/StartOperation"
	RunnerService_InspectOperation_FullMethodName = "/forge.runner.v1.RunnerService/InspectOperation"
	RunnerService_CancelOperation_FullMethodName  = "/forge.runner.v1.RunnerService/CancelOperation"
	RunnerService_StopWorkspace_FullMethodName    = "/forge.runner.v1.RunnerService/StopWorkspace"
	RunnerService_SealSnapshot_FullMethodName     = "/forge.runner.v1.RunnerService/SealSnapshot"
	RunnerService_ReleaseWorkspace_FullMethodName = "/forge.runner.v1.RunnerService/ReleaseWorkspace"
)

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerServiceClient interface {
	PrepareWorkspace(ctx context.Context, in *PrepareWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	AdoptWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*StopReceipt, error)
	StartOperation(ctx context.Context, in *StartOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	InspectOperation(ctx context.Context, in *InspectOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	CancelOperation(ctx context.Context, in *InspectOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	StopWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*StopReceipt, error)
	SealSnapshot(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*Snapshot, error)
	ReleaseWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*ReleaseResult, error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) PrepareWorkspace(ctx context.Context, in *PrepareWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, RunnerService_PrepareWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) AdoptWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*StopReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopReceipt)
	err := c.cc.Invoke(ctx, RunnerService_AdoptWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StartOperation(ctx context.Context, in *StartOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, RunnerService_StartOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) InspectOperation(ctx context.Context, in *InspectOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, RunnerService_InspectOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) CancelOperation(ctx context.Context, in *InspectOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, RunnerService_CancelOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) StopWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*StopReceipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopReceipt)
	err := c.cc.Invoke(ctx, RunnerService_StopWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) SealSnapshot(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, RunnerService_SealSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerServiceClient) ReleaseWorkspace(ctx context.Context, in *WorkspaceRequest, opts ...grpc.CallOption) (*ReleaseResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResult)
	err := c.cc.Invoke(ctx, RunnerService_ReleaseWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServiceServer is the server API for RunnerService service.
// All implementations must embed UnimplementedRunnerServiceServer
// for forward compatibility.
type RunnerServiceServer interface {
	PrepareWorkspace(context.Context, *PrepareWorkspaceRequest) (*Workspace, error)
	AdoptWorkspace(context.Context, *WorkspaceRequest) (*StopReceipt, error)
	StartOperation(context.Context, *StartOperationRequest) (*Operation, error)
	InspectOperation(context.Context, *InspectOperationRequest) (*Operation, error)
	CancelOperation(context.Context, *InspectOperationRequest) (*Operation, error)
	StopWorkspace(context.Context, *WorkspaceRequest) (*StopReceipt, error)
	SealSnapshot(context.Context, *WorkspaceRequest) (*Snapshot, error)
	ReleaseWorkspace(context.Context, *WorkspaceRequest) (*ReleaseResult, error)
	mustEmbedUnimplementedRunnerServiceServer()
}

// UnimplementedRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServiceServer struct{}

func (UnimplementedRunnerServiceServer) PrepareWorkspace(context.Context, *PrepareWorkspaceRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareWorkspace not implemented")
}
func (UnimplementedRunnerServiceServer) AdoptWorkspace(context.Context, *WorkspaceRequest) (*StopReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method AdoptWorkspace not implemented")
}
func (UnimplementedRunnerServiceServer) StartOperation(context.Context, *StartOperationRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOperation not implemented")
}
func (UnimplementedRunnerServiceServer) InspectOperation(context.Context, *InspectOperationRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectOperation not implemented")
}
func (UnimplementedRunnerServiceServer) CancelOperation(context.Context, *InspectOperationRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOperation not implemented")
}
func (UnimplementedRunnerServiceServer) StopWorkspace(context.Context, *WorkspaceRequest) (*StopReceipt, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWorkspace not implemented")
}
func (UnimplementedRunnerServiceServer) SealSnapshot(context.Context, *WorkspaceRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method SealSnapshot not implemented")
}
func (UnimplementedRunnerServiceServer) ReleaseWorkspace(context.Context, *WorkspaceRequest) (*ReleaseResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseWorkspace not implemented")
}
func (UnimplementedRunnerServiceServer) mustEmbedUnimplementedRunnerServiceServer() {}
func (UnimplementedRunnerServiceServer) testEmbeddedByValue()                       {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_PrepareWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).PrepareWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_PrepareWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).PrepareWorkspace(ctx, req.(*PrepareWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_AdoptWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).AdoptWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_AdoptWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).AdoptWorkspace(ctx, req.(*WorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StartOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).StartOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_StartOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).StartOperation(ctx, req.(*StartOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_InspectOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).InspectOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_InspectOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).InspectOperation(ctx, req.(*InspectOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_CancelOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).CancelOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_CancelOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).CancelOperation(ctx, req.(*InspectOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_StopWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).StopWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_StopWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).StopWorkspace(ctx, req.(*WorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_SealSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).SealSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_SealSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).SealSnapshot(ctx, req.(*WorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnerService_ReleaseWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServiceServer).ReleaseWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnerService_ReleaseWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServiceServer).ReleaseWorkspace(ctx, req.(*WorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forge.runner.v1.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareWorkspace",
			Handler:    _RunnerService_PrepareWorkspace_Handler,
		},
		{
			MethodName: "AdoptWorkspace",
			Handler:    _RunnerService_AdoptWorkspace_Handler,
		},
		{
			MethodName: "StartOperation",
			Handler:    _RunnerService_StartOperation_Handler,
		},
		{
			MethodName: "InspectOperation",
			Handler:    _RunnerService_InspectOperation_Handler,
		},
		{
			MethodName: "CancelOperation",
			Handler:    _RunnerService_CancelOperation_Handler,
		},
		{
			MethodName: "StopWorkspace",
			Handler:    _RunnerService_StopWorkspace_Handler,
		},
		{
			MethodName: "SealSnapshot",
			Handler:    _RunnerService_SealSnapshot_Handler,
		},
		{
			MethodName: "ReleaseWorkspace",
			Handler:    _RunnerService_ReleaseWorkspace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/runner/v1/runner.proto",
}
