// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/runner/v1/runner.proto

package runnerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolKind int32

const (
	ToolKind_TOOL_KIND_UNSPECIFIED ToolKind = 0
	ToolKind_TOOL_KIND_LIST_FILES  ToolKind = 1
	ToolKind_TOOL_KIND_READ_FILE   ToolKind = 2
	ToolKind_TOOL_KIND_SEARCH_CODE ToolKind = 3
	ToolKind_TOOL_KIND_APPLY_PATCH ToolKind = 4
	ToolKind_TOOL_KIND_RUN_COMMAND ToolKind = 5
	ToolKind_TOOL_KIND_GET_DIFF    ToolKind = 6
	ToolKind_TOOL_KIND_VERIFY      ToolKind = 7
)

// Enum value maps for ToolKind.
var (
	ToolKind_name = map[int32]string{
		0: "TOOL_KIND_UNSPECIFIED",
		1: "TOOL_KIND_LIST_FILES",
		2: "TOOL_KIND_READ_FILE",
		3: "TOOL_KIND_SEARCH_CODE",
		4: "TOOL_KIND_APPLY_PATCH",
		5: "TOOL_KIND_RUN_COMMAND",
		6: "TOOL_KIND_GET_DIFF",
		7: "TOOL_KIND_VERIFY",
	}
	ToolKind_value = map[string]int32{
		"TOOL_KIND_UNSPECIFIED": 0,
		"TOOL_KIND_LIST_FILES":  1,
		"TOOL_KIND_READ_FILE":   2,
		"TOOL_KIND_SEARCH_CODE": 3,
		"TOOL_KIND_APPLY_PATCH": 4,
		"TOOL_KIND_RUN_COMMAND": 5,
		"TOOL_KIND_GET_DIFF":    6,
		"TOOL_KIND_VERIFY":      7,
	}
)

func (x ToolKind) Enum() *ToolKind {
	p := new(ToolKind)
	*p = x
	return p
}

func (x ToolKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runner_v1_runner_proto_enumTypes[0].Descriptor()
}

func (ToolKind) Type() protoreflect.EnumType {
	return &file_proto_runner_v1_runner_proto_enumTypes[0]
}

func (x ToolKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolKind.Descriptor instead.
func (ToolKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{0}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PREPARED    OperationStatus = 1
	OperationStatus_OPERATION_STATUS_RUNNING     OperationStatus = 2
	OperationStatus_OPERATION_STATUS_SUCCEEDED   OperationStatus = 3
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 4
	OperationStatus_OPERATION_STATUS_CANCELLED   OperationStatus = 5
	OperationStatus_OPERATION_STATUS_UNKNOWN     OperationStatus = 6
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PREPARED",
		2: "OPERATION_STATUS_RUNNING",
		3: "OPERATION_STATUS_SUCCEEDED",
		4: "OPERATION_STATUS_FAILED",
		5: "OPERATION_STATUS_CANCELLED",
		6: "OPERATION_STATUS_UNKNOWN",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PREPARED":    1,
		"OPERATION_STATUS_RUNNING":     2,
		"OPERATION_STATUS_SUCCEEDED":   3,
		"OPERATION_STATUS_FAILED":      4,
		"OPERATION_STATUS_CANCELLED":   5,
		"OPERATION_STATUS_UNKNOWN":     6,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_runner_v1_runner_proto_enumTypes[1].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_proto_runner_v1_runner_proto_enumTypes[1]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{1}
}

type ResourceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceID) Reset() {
	*x = ResourceID{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceID) ProtoMessage() {}

func (x *ResourceID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceID.ProtoReflect.Descriptor instead.
func (*ResourceID) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WorkspaceBinding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        *ResourceID            `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId           *ResourceID            `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkspaceId     *ResourceID            `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Epoch           uint64                 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CapabilityGrant string                 `protobuf:"bytes,5,opt,name=capability_grant,json=capabilityGrant,proto3" json:"capability_grant,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkspaceBinding) Reset() {
	*x = WorkspaceBinding{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceBinding) ProtoMessage() {}

func (x *WorkspaceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceBinding.ProtoReflect.Descriptor instead.
func (*WorkspaceBinding) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{1}
}

func (x *WorkspaceBinding) GetTenantId() *ResourceID {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *WorkspaceBinding) GetRunId() *ResourceID {
	if x != nil {
		return x.RunId
	}
	return nil
}

func (x *WorkspaceBinding) GetWorkspaceId() *ResourceID {
	if x != nil {
		return x.WorkspaceId
	}
	return nil
}

func (x *WorkspaceBinding) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *WorkspaceBinding) GetCapabilityGrant() string {
	if x != nil {
		return x.CapabilityGrant
	}
	return ""
}

type PrepareWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       *WorkspaceBinding      `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareWorkspaceRequest) Reset() {
	*x = PrepareWorkspaceRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareWorkspaceRequest) ProtoMessage() {}

func (x *PrepareWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*PrepareWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareWorkspaceRequest) GetBinding() *WorkspaceBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *PrepareWorkspaceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PrepareWorkspaceRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type WorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       *WorkspaceBinding      `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceRequest) Reset() {
	*x = WorkspaceRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceRequest) ProtoMessage() {}

func (x *WorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{3}
}

func (x *WorkspaceRequest) GetBinding() *WorkspaceBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type InspectOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       *WorkspaceBinding      `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	OperationId   *ResourceID            `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectOperationRequest) Reset() {
	*x = InspectOperationRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectOperationRequest) ProtoMessage() {}

func (x *InspectOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectOperationRequest.ProtoReflect.Descriptor instead.
func (*InspectOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{4}
}

func (x *InspectOperationRequest) GetBinding() *WorkspaceBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *InspectOperationRequest) GetOperationId() *ResourceID {
	if x != nil {
		return x.OperationId
	}
	return nil
}

type StartOperationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Binding          *WorkspaceBinding      `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	OperationId      *ResourceID            `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	ToolKind         ToolKind               `protobuf:"varint,4,opt,name=tool_kind,json=toolKind,proto3,enum=forge.runner.v1.ToolKind" json:"tool_kind,omitempty"`
	// Bounded canonical JSON for the known tool schema. Bytes are preserved
	// exactly: re-encoding JSON here would invalidate the approved args_hash.
	CanonicalArgsJson []byte                 `protobuf:"bytes,5,opt,name=canonical_args_json,json=canonicalArgsJson,proto3" json:"canonical_args_json,omitempty"`
	ArgsSha256        string                 `protobuf:"bytes,6,opt,name=args_sha256,json=argsSha256,proto3" json:"args_sha256,omitempty"`
	PolicyVersion     string                 `protobuf:"bytes,7,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Deadline          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartOperationRequest) Reset() {
	*x = StartOperationRequest{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartOperationRequest) ProtoMessage() {}

func (x *StartOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartOperationRequest.ProtoReflect.Descriptor instead.
func (*StartOperationRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{5}
}

func (x *StartOperationRequest) GetBinding() *WorkspaceBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *StartOperationRequest) GetOperationId() *ResourceID {
	if x != nil {
		return x.OperationId
	}
	return nil
}

func (x *StartOperationRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *StartOperationRequest) GetToolKind() ToolKind {
	if x != nil {
		return x.ToolKind
	}
	return ToolKind_TOOL_KIND_UNSPECIFIED
}

func (x *StartOperationRequest) GetCanonicalArgsJson() []byte {
	if x != nil {
		return x.CanonicalArgsJson
	}
	return nil
}

func (x *StartOperationRequest) GetArgsSha256() string {
	if x != nil {
		return x.ArgsSha256
	}
	return ""
}

func (x *StartOperationRequest) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *StartOperationRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type Workspace struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          *ResourceID            `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId             *ResourceID            `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Id                *ResourceID            `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	SourceId          string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ProfileId         string                 `protobuf:"bytes,5,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Epoch             uint64                 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Revision          uint64                 `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	ActiveOperationId *ResourceID            `protobuf:"bytes,8,opt,name=active_operation_id,json=activeOperationId,proto3" json:"active_operation_id,omitempty"`
	Adopting          bool                   `protobuf:"varint,9,opt,name=adopting,proto3" json:"adopting,omitempty"`
	Released          bool                   `protobuf:"varint,10,opt,name=released,proto3" json:"released,omitempty"`
	BaselineSha256    string                 `protobuf:"bytes,11,opt,name=baseline_sha256,json=baselineSha256,proto3" json:"baseline_sha256,omitempty"`
	Stopped           bool                   `protobuf:"varint,12,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{6}
}

func (x *Workspace) GetTenantId() *ResourceID {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *Workspace) GetRunId() *ResourceID {
	if x != nil {
		return x.RunId
	}
	return nil
}

func (x *Workspace) GetId() *ResourceID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Workspace) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Workspace) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Workspace) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Workspace) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Workspace) GetActiveOperationId() *ResourceID {
	if x != nil {
		return x.ActiveOperationId
	}
	return nil
}

func (x *Workspace) GetAdopting() bool {
	if x != nil {
		return x.Adopting
	}
	return false
}

func (x *Workspace) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *Workspace) GetBaselineSha256() string {
	if x != nil {
		return x.BaselineSha256
	}
	return ""
}

func (x *Workspace) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      *ResourceID            `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RunId         *ResourceID            `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ByteSize      int64                  `protobuf:"varint,6,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactRef) GetTenantId() *ResourceID {
	if x != nil {
		return x.TenantId
	}
	return nil
}

func (x *ArtifactRef) GetRunId() *ResourceID {
	if x != nil {
		return x.RunId
	}
	return nil
}

func (x *ArtifactRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ArtifactRef) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ArtifactRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactRef) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

type Operation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Request             *StartOperationRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Status              OperationStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=forge.runner.v1.OperationStatus" json:"status,omitempty"`
	JobId               string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	BeforeSha256        string                 `protobuf:"bytes,4,opt,name=before_sha256,json=beforeSha256,proto3" json:"before_sha256,omitempty"`
	ExpectedAfterSha256 string                 `protobuf:"bytes,5,opt,name=expected_after_sha256,json=expectedAfterSha256,proto3" json:"expected_after_sha256,omitempty"`
	AfterSha256         string                 `protobuf:"bytes,6,opt,name=after_sha256,json=afterSha256,proto3" json:"after_sha256,omitempty"`
	AfterRevision       uint64                 `protobuf:"varint,7,opt,name=after_revision,json=afterRevision,proto3" json:"after_revision,omitempty"`
	ResultJson          []byte                 `protobuf:"bytes,8,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	Receipt             *ArtifactRef           `protobuf:"bytes,9,opt,name=receipt,proto3" json:"receipt,omitempty"`
	Error               string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	CancelRequested     bool                   `protobuf:"varint,11,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	ResultTruncated     bool                   `protobuf:"varint,12,opt,name=result_truncated,json=resultTruncated,proto3" json:"result_truncated,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{8}
}

func (x *Operation) GetRequest() *StartOperationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Operation) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *Operation) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Operation) GetBeforeSha256() string {
	if x != nil {
		return x.BeforeSha256
	}
	return ""
}

func (x *Operation) GetExpectedAfterSha256() string {
	if x != nil {
		return x.ExpectedAfterSha256
	}
	return ""
}

func (x *Operation) GetAfterSha256() string {
	if x != nil {
		return x.AfterSha256
	}
	return ""
}

func (x *Operation) GetAfterRevision() uint64 {
	if x != nil {
		return x.AfterRevision
	}
	return 0
}

func (x *Operation) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *Operation) GetReceipt() *ArtifactRef {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *Operation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Operation) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

func (x *Operation) GetResultTruncated() bool {
	if x != nil {
		return x.ResultTruncated
	}
	return false
}

type StopReceipt struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Workspace          *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	NoActiveOperations bool                   `protobuf:"varint,2,opt,name=no_active_operations,json=noActiveOperations,proto3" json:"no_active_operations,omitempty"`
	Receipt            *ArtifactRef           `protobuf:"bytes,3,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopReceipt) Reset() {
	*x = StopReceipt{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReceipt) ProtoMessage() {}

func (x *StopReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReceipt.ProtoReflect.Descriptor instead.
func (*StopReceipt) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{9}
}

func (x *StopReceipt) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *StopReceipt) GetNoActiveOperations() bool {
	if x != nil {
		return x.NoActiveOperations
	}
	return false
}

func (x *StopReceipt) GetReceipt() *ArtifactRef {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Artifact      *ArtifactRef           `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{10}
}

func (x *Snapshot) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *Snapshot) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Snapshot) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type ReleaseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   *ResourceID            `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Released      bool                   `protobuf:"varint,2,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResult) Reset() {
	*x = ReleaseResult{}
	mi := &file_proto_runner_v1_runner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResult) ProtoMessage() {}

func (x *ReleaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_v1_runner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResult.ProtoReflect.Descriptor instead.
func (*ReleaseResult) Descriptor() ([]byte, []int) {
	return file_proto_runner_v1_runner_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseResult) GetWorkspaceId() *ResourceID {
	if x != nil {
		return x.WorkspaceId
	}
	return nil
}

func (x *ReleaseResult) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

var File_proto_runner_v1_runner_proto protoreflect.FileDescriptor

const file_proto_runner_v1_runner_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/runner/v1/runner.proto\x12\x0fforge.runner.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\n" +
	"ResourceID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x81\x02\n" +
	"\x10WorkspaceBinding\x128\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\btenantId\x122\n" +
	"\x06run_id\x18\x02 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\x05runId\x12>\n" +
	"\fworkspace_id\x18\x03 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\vworkspaceId\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x04R\x05epoch\x12)\n" +
	"\x10capability_grant\x18\x05 \x01(\tR\x0fcapabilityGrant\"\x92\x01\n" +
	"\x17PrepareWorkspaceRequest\x12;\n" +
	"\abinding\x18\x01 \x01(\v2!.forge.runner.v1.WorkspaceBindingR\abinding\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\"O\n" +
	"\x10WorkspaceRequest\x12;\n" +
	"\abinding\x18\x01 \x01(\v2!.forge.runner.v1.WorkspaceBindingR\abinding\"\x96\x01\n" +
	"\x17InspectOperationRequest\x12;\n" +
	"\abinding\x18\x01 \x01(\v2!.forge.runner.v1.WorkspaceBindingR\abinding\x12>\n" +
	"\foperation_id\x18\x02 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\voperationId\"\xa9\x03\n" +
	"\x15StartOperationRequest\x12;\n" +
	"\abinding\x18\x01 \x01(\v2!.forge.runner.v1.WorkspaceBindingR\abinding\x12>\n" +
	"\foperation_id\x18\x02 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\voperationId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\x126\n" +
	"\ttool_kind\x18\x04 \x01(\x0e2\x19.forge.runner.v1.ToolKindR\btoolKind\x12.\n" +
	"\x13canonical_args_json\x18\x05 \x01(\fR\x11canonicalArgsJson\x12\x1f\n" +
	"\vargs_sha256\x18\x06 \x01(\tR\n" +
	"argsSha256\x12%\n" +
	"\x0epolicy_version\x18\a \x01(\tR\rpolicyVersion\x126\n" +
	"\bdeadline\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xdc\x03\n" +
	"\tWorkspace\x128\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\btenantId\x122\n" +
	"\x06run_id\x18\x02 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\x05runId\x12+\n" +
	"\x02id\x18\x03 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x05 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x04R\x05epoch\x12\x1a\n" +
	"\brevision\x18\a \x01(\x04R\brevision\x12K\n" +
	"\x13active_operation_id\x18\b \x01(\v2\x1b.forge.runner.v1.ResourceIDR\x11activeOperationId\x12\x1a\n" +
	"\badopting\x18\t \x01(\bR\badopting\x12\x1a\n" +
	"\breleased\x18\n" +
	" \x01(\bR\breleased\x12'\n" +
	"\x0fbaseline_sha256\x18\v \x01(\tR\x0ebaselineSha256\x12\x18\n" +
	"\astopped\x18\f \x01(\bR\astopped\"\xe3\x01\n" +
	"\vArtifactRef\x128\n" +
	"\ttenant_id\x18\x01 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\btenantId\x122\n" +
	"\x06run_id\x18\x02 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\x05runId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x1b\n" +
	"\tbyte_size\x18\x06 \x01(\x03R\bbyteSize\"\x86\x04\n" +
	"\tOperation\x12@\n" +
	"\arequest\x18\x01 \x01(\v2&.forge.runner.v1.StartOperationRequestR\arequest\x128\n" +
	"\x06status\x18\x02 \x01(\x0e2 .forge.runner.v1.OperationStatusR\x06status\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12#\n" +
	"\rbefore_sha256\x18\x04 \x01(\tR\fbeforeSha256\x122\n" +
	"\x15expected_after_sha256\x18\x05 \x01(\tR\x13expectedAfterSha256\x12!\n" +
	"\fafter_sha256\x18\x06 \x01(\tR\vafterSha256\x12%\n" +
	"\x0eafter_revision\x18\a \x01(\x04R\rafterRevision\x12\x1f\n" +
	"\vresult_json\x18\b \x01(\fR\n" +
	"resultJson\x126\n" +
	"\areceipt\x18\t \x01(\v2\x1c.forge.runner.v1.ArtifactRefR\areceipt\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12)\n" +
	"\x10cancel_requested\x18\v \x01(\bR\x0fcancelRequested\x12)\n" +
	"\x10result_truncated\x18\f \x01(\bR\x0fresultTruncated\"\xb1\x01\n" +
	"\vStopReceipt\x128\n" +
	"\tworkspace\x18\x01 \x01(\v2\x1a.forge.runner.v1.WorkspaceR\tworkspace\x120\n" +
	"\x14no_active_operations\x18\x02 \x01(\bR\x12noActiveOperations\x126\n" +
	"\areceipt\x18\x03 \x01(\v2\x1c.forge.runner.v1.ArtifactRefR\areceipt\"\x96\x01\n" +
	"\bSnapshot\x128\n" +
	"\tworkspace\x18\x01 \x01(\v2\x1a.forge.runner.v1.WorkspaceR\tworkspace\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x128\n" +
	"\bartifact\x18\x03 \x01(\v2\x1c.forge.runner.v1.ArtifactRefR\bartifact\"k\n" +
	"\rReleaseResult\x12>\n" +
	"\fworkspace_id\x18\x01 \x01(\v2\x1b.forge.runner.v1.ResourceIDR\vworkspaceId\x12\x1a\n" +
	"\breleased\x18\x02 \x01(\bR\breleased*\xd7\x01\n" +
	"\bToolKind\x12\x19\n" +
	"\x15TOOL_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TOOL_KIND_LIST_FILES\x10\x01\x12\x17\n" +
	"\x13TOOL_KIND_READ_FILE\x10\x02\x12\x19\n" +
	"\x15TOOL_KIND_SEARCH_CODE\x10\x03\x12\x19\n" +
	"\x15TOOL_KIND_APPLY_PATCH\x10\x04\x12\x19\n" +
	"\x15TOOL_KIND_RUN_COMMAND\x10\x05\x12\x16\n" +
	"\x12TOOL_KIND_GET_DIFF\x10\x06\x12\x14\n" +
	"\x10TOOL_KIND_VERIFY\x10\a*\xeb\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19OPERATION_STATUS_PREPARED\x10\x01\x12\x1c\n" +
	"\x18OPERATION_STATUS_RUNNING\x10\x02\x12\x1e\n" +
	"\x1aOPERATION_STATUS_SUCCEEDED\x10\x03\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x04\x12\x1e\n" +
	"\x1aOPERATION_STATUS_CANCELLED\x10\x05\x12\x1c\n" +
	"\x18OPERATION_STATUS_UNKNOWN\x10\x062\xbc\x05\n" +
	"\rRunnerService\x12X\n" +
	"\x10PrepareWorkspace\x12(.forge.runner.v1.PrepareWorkspaceRequest\x1a\x1a.forge.runner.v1.Workspace\x12Q\n" +
	"\x0eAdoptWorkspace\x12!.forge.runner.v1.WorkspaceRequest\x1a\x1c.forge.runner.v1.StopReceipt\x12T\n" +
	"\x0eStartOperation\x12&.forge.runner.v1.StartOperationRequest\x1a\x1a.forge.runner.v1.Operation\x12X\n" +
	"\x10InspectOperation\x12(.forge.runner.v1.InspectOperationRequest\x1a\x1a.forge.runner.v1.Operation\x12W\n" +
	"\x0fCancelOperation\x12(.forge.runner.v1.InspectOperationRequest\x1a\x1a.forge.runner.v1.Operation\x12P\n" +
	"\rStopWorkspace\x12!.forge.runner.v1.WorkspaceRequest\x1a\x1c.forge.runner.v1.StopReceipt\x12L\n" +
	"\fSealSnapshot\x12!.forge.runner.v1.WorkspaceRequest\x1a\x19.forge.runner.v1.Snapshot\x12U\n" +
	"\x10ReleaseWorkspace\x12!.forge.runner.v1.WorkspaceRequest\x1a\x1e.forge.runner.v1.ReleaseResultB?Z=github.com/JDinSeattle/forge-runtime/proto/runner/v1;runnerv1b\x06proto3"

var (
	file_proto_runner_v1_runner_proto_rawDescOnce sync.Once
	file_proto_runner_v1_runner_proto_rawDescData []byte
)

func file_proto_runner_v1_runner_proto_rawDescGZIP() []byte {
	file_proto_runner_v1_runner_proto_rawDescOnce.Do(func() {
		file_proto_runner_v1_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_runner_v1_runner_proto_rawDesc), len(file_proto_runner_v1_runner_proto_rawDesc)))
	})
	return file_proto_runner_v1_runner_proto_rawDescData
}

var file_proto_runner_v1_runner_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_runner_v1_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_runner_v1_runner_proto_goTypes = []any{
	(ToolKind)(0),                   // 0: forge.runner.v1.ToolKind
	(OperationStatus)(0),            // 1: forge.runner.v1.OperationStatus
	(*ResourceID)(nil),              // 2: forge.runner.v1.ResourceID
	(*WorkspaceBinding)(nil),        // 3: forge.runner.v1.WorkspaceBinding
	(*PrepareWorkspaceRequest)(nil), // 4: forge.runner.v1.PrepareWorkspaceRequest
	(*WorkspaceRequest)(nil),        // 5: forge.runner.v1.WorkspaceRequest
	(*InspectOperationRequest)(nil), // 6: forge.runner.v1.InspectOperationRequest
	(*StartOperationRequest)(nil),   // 7: forge.runner.v1.StartOperationRequest
	(*Workspace)(nil),               // 8: forge.runner.v1.Workspace
	(*ArtifactRef)(nil),             // 9: forge.runner.v1.ArtifactRef
	(*Operation)(nil),               // 10: forge.runner.v1.Operation
	(*StopReceipt)(nil),             // 11: forge.runner.v1.StopReceipt
	(*Snapshot)(nil),                // 12: forge.runner.v1.Snapshot
	(*ReleaseResult)(nil),           // 13: forge.runner.v1.ReleaseResult
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_proto_runner_v1_runner_proto_depIdxs = []int32{
	2,  // 0: forge.runner.v1.WorkspaceBinding.tenant_id:type_name -> forge.runner.v1.ResourceID
	2,  // 1: forge.runner.v1.WorkspaceBinding.run_id:type_name -> forge.runner.v1.ResourceID
	2,  // 2: forge.runner.v1.WorkspaceBinding.workspace_id:type_name -> forge.runner.v1.ResourceID
	3,  // 3: forge.runner.v1.PrepareWorkspaceRequest.binding:type_name -> forge.runner.v1.WorkspaceBinding
	3,  // 4: forge.runner.v1.WorkspaceRequest.binding:type_name -> forge.runner.v1.WorkspaceBinding
	3,  // 5: forge.runner.v1.InspectOperationRequest.binding:type_name -> forge.runner.v1.WorkspaceBinding
	2,  // 6: forge.runner.v1.InspectOperationRequest.operation_id:type_name -> forge.runner.v1.ResourceID
	3,  // 7: forge.runner.v1.StartOperationRequest.binding:type_name -> forge.runner.v1.WorkspaceBinding
	2,  // 8: forge.runner.v1.StartOperationRequest.operation_id:type_name -> forge.runner.v1.ResourceID
	0,  // 9: forge.runner.v1.StartOperationRequest.tool_kind:type_name -> forge.runner.v1.ToolKind
	14, // 10: forge.runner.v1.StartOperationRequest.deadline:type_name -> google.protobuf.Timestamp
	2,  // 11: forge.runner.v1.Workspace.tenant_id:type_name -> forge.runner.v1.ResourceID
	2,  // 12: forge.runner.v1.Workspace.run_id:type_name -> forge.runner.v1.ResourceID
	2,  // 13: forge.runner.v1.Workspace.id:type_name -> forge.runner.v1.ResourceID
	2,  // 14: forge.runner.v1.Workspace.active_operation_id:type_name -> forge.runner.v1.ResourceID
	2,  // 15: forge.runner.v1.ArtifactRef.tenant_id:type_name -> forge.runner.v1.ResourceID
	2,  // 16: forge.runner.v1.ArtifactRef.run_id:type_name -> forge.runner.v1.ResourceID
	7,  // 17: forge.runner.v1.Operation.request:type_name -> forge.runner.v1.StartOperationRequest
	1,  // 18: forge.runner.v1.Operation.status:type_name -> forge.runner.v1.OperationStatus
	9,  // 19: forge.runner.v1.Operation.receipt:type_name -> forge.runner.v1.ArtifactRef
	8,  // 20: forge.runner.v1.StopReceipt.workspace:type_name -> forge.runner.v1.Workspace
	9,  // 21: forge.runner.v1.StopReceipt.receipt:type_name -> forge.runner.v1.ArtifactRef
	8,  // 22: forge.runner.v1.Snapshot.workspace:type_name -> forge.runner.v1.Workspace
	9,  // 23: forge.runner.v1.Snapshot.artifact:type_name -> forge.runner.v1.ArtifactRef
	2,  // 24: forge.runner.v1.ReleaseResult.workspace_id:type_name -> forge.runner.v1.ResourceID
	4,  // 25: forge.runner.v1.RunnerService.PrepareWorkspace:input_type -> forge.runner.v1.PrepareWorkspaceRequest
	5,  // 26: forge.runner.v1.RunnerService.AdoptWorkspace:input_type -> forge.runner.v1.WorkspaceRequest
	7,  // 27: forge.runner.v1.RunnerService.StartOperation:input_type -> forge.runner.v1.StartOperationRequest
	6,  // 28: forge.runner.v1.RunnerService.InspectOperation:input_type -> forge.runner.v1.InspectOperationRequest
	6,  // 29: forge.runner.v1.RunnerService.CancelOperation:input_type -> forge.runner.v1.InspectOperationRequest
	5,  // 30: forge.runner.v1.RunnerService.StopWorkspace:input_type -> forge.runner.v1.WorkspaceRequest
	5,  // 31: forge.runner.v1.RunnerService.SealSnapshot:input_type -> forge.runner.v1.WorkspaceRequest
	5,  // 32: forge.runner.v1.RunnerService.ReleaseWorkspace:input_type -> forge.runner.v1.WorkspaceRequest
	8,  // 33: forge.runner.v1.RunnerService.PrepareWorkspace:output_type -> forge.runner.v1.Workspace
	11, // 34: forge.runner.v1.RunnerService.AdoptWorkspace:output_type -> forge.runner.v1.StopReceipt
	10, // 35: forge.runner.v1.RunnerService.StartOperation:output_type -> forge.runner.v1.Operation
	10, // 36: forge.runner.v1.RunnerService.InspectOperation:output_type -> forge.runner.v1.Operation
	10, // 37: forge.runner.v1.RunnerService.CancelOperation:output_type -> forge.runner.v1.Operation
	11, // 38: forge.runner.v1.RunnerService.StopWorkspace:output_type -> forge.runner.v1.StopReceipt
	12, // 39: forge.runner.v1.RunnerService.SealSnapshot:output_type -> forge.runner.v1.Snapshot
	13, // 40: forge.runner.v1.RunnerService.ReleaseWorkspace:output_type -> forge.runner.v1.ReleaseResult
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_runner_v1_runner_proto_init() }
func file_proto_runner_v1_runner_proto_init() {
	if File_proto_runner_v1_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_runner_v1_runner_proto_rawDesc), len(file_proto_runner_v1_runner_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runner_v1_runner_proto_goTypes,
		DependencyIndexes: file_proto_runner_v1_runner_proto_depIdxs,
		EnumInfos:         file_proto_runner_v1_runner_proto_enumTypes,
		MessageInfos:      file_proto_runner_v1_runner_proto_msgTypes,
	}.Build()
	File_proto_runner_v1_runner_proto = out.File
	file_proto_runner_v1_runner_proto_goTypes = nil
	file_proto_runner_v1_runner_proto_depIdxs = nil
}
